### ISSUE TITLE
numpy error

### ISSUE THREAD

**Issue by aledolme** [pulp-platform/pulp-runtime#35]
Hello everyone. 
I'm having some trouble in running the "hello-world" example. In particular, despite the fact that numpy is corretly installed and updated, slm_hyper.py file execution reports the following issue:

  File "$HOME/pulp-runtime/bin/slm_hyper.py", line 18, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

Does anyone encounter this problem? I've already tried to set up manually python path in the file, updating the NumPy package, but the error still remain.

Thanks you

**Comment by AmrBadra25** [comment]
Hello Could u please provide how did u solve this issue Since I am encountering the same issue Thanks a lot in advance
